name: multi-bot-app
region: fra
build:
  builder: nixpacks
  build_command: |
    pip install --upgrade pip
    pip install -r requirements.txt
run:
  command: python coordinator.py
  ports:
    - port: 8000
      http: true
    - port: 5001
      http: true
